application-description: This application is mainly for Student Registration - register, retrieve, update and delete student records
application-version: 0.0.1

spring:
  application:
    name: student-service
  data:
    mongodb:
     uri: mongodb://localhost:27017/STUDENT_TEST
     
springdoc:
 swagger-ui:
   path: /swagger-ui.html
   operationsSorter: alpha
   supportedSubmitMethods: get, put, post, delete, options, head, patch, trace
   
server:
 port: 9191
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://prateek:prateek@localhost:8761/eureka