spring:
  application:
    name: student-service
  data:
    mongodb:
     uri: mongodb://localhost:27017/STUDENT_TEST
   
server:
 port: 9191
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://prateek:prateek@localhost:8761/eureka